#!/bin/sh
set -eux

OUT_DIR='things'

mkdir -p "$OUT_DIR"

for layout in '4x5' '4x6' '5x6' '6x6'; do
    { echo "generating layout ${layout} ============="; } 2>/dev/null

    # we do not need to patch since the repo stores the design for 4x5
    if { [ "$layout" != "4x5" ]; } 2>/dev/null; then
        patch -p1 < "${layout}.patch" -u
    fi

    # generate the scad files
    lein run src/dactyl_keyboard/dactyl.clj

    LAYOUT_DIR="$OUT_DIR/$layout"
    mkdir "$LAYOUT_DIR"

    cp "$OUT_DIR/right.scad" "$LAYOUT_DIR/right-${layout}.scad"
    cp "$OUT_DIR/left.scad" "$LAYOUT_DIR/left-${layout}.scad"
    cp "$OUT_DIR/right-plate.scad" "$LAYOUT_DIR/right-${layout}-plate.scad"

    # run openscad in parallel
    openscad -o "$LAYOUT_DIR/right-${layout}-plate.dxf" "$LAYOUT_DIR/right-${layout}-plate.scad" >/dev/null 2>&1 &
    openscad -o "$LAYOUT_DIR/right-${layout}.stl" "$LAYOUT_DIR/right-${layout}.scad" >/dev/null 2>&1 &
    openscad -o "$LAYOUT_DIR/left-${layout}.stl" "$LAYOUT_DIR/left-${layout}.scad" >/dev/null 2>&1 &
    { wait; } 2>/dev/null

    # restore if patched
    if { [ "$layout" != "4x5" ]; } 2>/dev/null; then
        git restore src/dactyl_keyboard/dactyl.clj
    fi
done
rm "$OUT_DIR/"*.scad
